'use strict';
const icons={layers:'M12 3 3 8l9 5 9-5-9-5ZM3 12l9 5 9-5M3 16l9 5 9-5',sun:'M12 3v2m0 14v2M3 12h2m14 0h2M5.6 5.6 1.4 1.4m10 10 1.4 1.4M5.6 18.4 1.4-1.4m10-10 1.4-1.4M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',list:'M9 6h12M9 12h12M9 18h12M3 6h.01M3 12h.01M3 18h.01',book:'M12 5v15M3 4h5a4 4 0 0 1 4 2 4 4 0 0 1 4-2h5v15h-5a4 4 0 0 0-4 2 4 4 0 0 0-4-2H3V4Z',checkCircle:'M21 11v1a9 9 0 1 1-5.4-8.2M8 11l4 4 9-10',check:'m5 12 4 4L19 6',sparkles:'m12 3 2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3L12 3ZM20 2v4m-2-2h4',info:'M12 16v-4m0-4h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',rotate:'M3 3v5h5M3.5 8A9 9 0 1 1 3 15',arrowRight:'M4 12h16m-6-6 6 6-6 6',arrowUpRight:'M6 18 18 6M6 6h12v12',clock:'M12 7v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',search:'m21 21-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',chat:'M21 11a8 8 0 0 1-8 8H7l-4 3V5a2 2 0 0 1 2-2h8a8 8 0 0 1 8 8ZM7 8h9M7 12h6',leaf:'M20 3c-2 6 3 13-5 17C6 24 0 13 6 8c3-3 8-1 14-5ZM7 17l8-8',file:'M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6ZM14 2v6h6M8 13h8M8 17h5',calendar:'M8 2v4m8-4v4M3 10h18M5 4h14a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2',paperclip:'m9 17 7-7a3 3 0 0 0-4-4l-8 8a5 5 0 0 0 7 7l9-9a7 7 0 0 0-10-10',x:'M6 6l12 12M6 18 18 6'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.file}"></path></svg>`;
function paintIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));}
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const original=window.DEMO;
let tasks=original.tasks.map(t=>({...t})),view='today',filter='all',toastTimer;
const materialUrl=id=>'materials/sample-reading.html?type='+encodeURIComponent(id);
const todayParts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());
const datePart=name=>todayParts.find(x=>x.type===name).value;
const today=new Date(`${datePart('year')}-${datePart('month')}-${datePart('day')}T12:00:00Z`);
const sampleDate=offset=>{const d=new Date(today);d.setUTCDate(d.getUTCDate()+offset);return d;};
const dayText=offset=>offset===0?'今天':offset===1?'明天':new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',timeZone:'UTC'}).format(sampleDate(offset));
function notify(message){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').classList.add('visible');toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2800);}
function setView(next){view=next;filter='all';$('search').value='';document.querySelectorAll('[data-filter]').forEach(b=>{const active=b.dataset.filter==='all';b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});render();}
function toggle(id){const task=tasks.find(t=>t.id===id);if(!task)return;task.done=!task.done;render();notify(task.done?'已移入「已完成」 · 仅演示当前页面':'已恢复到待办 · 仅演示当前页面');}
function matching(t,query){return (filter==='all'||t.category===filter)&&[t.title,t.group,t.description,t.type].join(' ').toLowerCase().includes(query);}
function taskCard(t){return `<article class="task-card ${t.done?'done':''}"><button role="checkbox" aria-checked="${t.done}" aria-label="${t.done?'恢复待办':'标记完成'}：${esc(t.title)}" class="check-task" data-toggle="${t.id}">${t.done?icon('check'):''}</button><div class="task-body"><div class="task-top"><button class="task-title" data-detail="${t.id}">${esc(t.title)}</button><button class="task-menu" aria-label="查看详情：${esc(t.title)}" data-detail="${t.id}">${icon('arrowUpRight')}</button></div><p class="task-description">${esc(t.description)}</p><div class="task-meta"><span class="tag ${t.category}">${esc(t.group)}</span><span class="task-date ${t.day===0&&!t.done?'soon':''}">${icon('calendar')}${t.done?'已完成':esc(dayText(t.day))+' · '+esc(t.time)}</span>${t.material.length?`<button class="attachment" data-detail="${t.id}" aria-label="查看 ${esc(t.title)} 的关联资料">${icon('paperclip')}${t.material.length} 份资料</button>`:''}</div></div></article>`;}
function miniMaterial(m){return `<a class="reading-card" href="${materialUrl(m.id)}" target="_blank" rel="noopener"><span class="file-icon">${icon('file')}</span><span><strong>${esc(m.title)}</strong><small>${esc(m.format)} · ${esc(m.kind)}</small></span>${icon('arrowUpRight')}</a>`;}
function libraryCard(m){return `<article class="library-card"><div class="file-icon">${icon('file')}</div><h3>${esc(m.title)}</h3><p>${esc(m.description)}</p><a href="${materialUrl(m.id)}" target="_blank" rel="noopener">打开示例 ${'↗'}</a><button data-detail="${m.task}">关联任务 →</button></article>`;}
const viewInfo={today:{crumb:'今天',heading:'给今天一点秩序',lead:'先选一件值得专注的事，其余的，我们慢慢来。',section:'今天的清单',description:'轻重缓急，一眼就清楚。'},all:{crumb:'全部任务',heading:'每件事，都有自己的位置',lead:'把课程、项目和个人安排放在一起，留出专注的空间。',section:'全部未完成',description:'先想清楚下一步，再动手。'},library:{crumb:'资料库',heading:'要读的，都在手边',lead:'文章、题目和笔记，从任务直接抵达材料。',section:'我的资料',description:'当前仅展示原创占位材料，不含真实阅读文件。'},done:{crumb:'已完成',heading:'走过的每一步，都算数',lead:'完成之后收好，需要时还能找回来。',section:'完成记录',description:'这里保留任务说明和关联资料。'}};
function render(){const info=viewInfo[view],query=$('search').value.trim().toLowerCase();$('crumb').textContent=info.crumb;$('page-title').innerHTML=esc(info.heading)+'<span>。</span>';$('page-lead').textContent=info.lead;$('section-description').textContent=info.description;const selected=view==='library'?original.materials.filter(m=>[m.title,m.subtitle,m.description].join(' ').toLowerCase().includes(query)):tasks.filter(t=>(view==='done'?t.done:!t.done)&&(view!=='today'||t.focus)&&matching(t,query));$('section-title').innerHTML=esc(info.section)+` <span>${selected.length}</span>`;$('filters').hidden=view==='library';$('items').className=view==='library'?'library-grid':'';$('items').innerHTML=selected.length?selected.map(view==='library'?libraryCard:taskCard).join(''):`<div class="empty">${query||filter!=='all'?'没有找到符合条件的内容，试试其他关键词。':view==='today'?'今天的演示任务已完成，给自己一点休息时间。':'这里暂时没有内容。'}</div>`;$('list-footer').hidden=view==='library'||view==='done';$('reading-section').hidden=view!=='today';$('focus-card').hidden=view!=='today';document.querySelectorAll('.nav-item').forEach(b=>{const active=b.dataset.view===view;b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});$('today-count').textContent=tasks.filter(t=>t.focus&&!t.done).length;$('all-count').textContent=tasks.filter(t=>!t.done).length;const focusTasks=tasks.filter(t=>t.focus),done=focusTasks.filter(t=>t.done).length;$('progress-number').innerHTML=done+`<span>/ ${focusTasks.length}</span>`;$('progress-fill').style.width=(done/focusTasks.length*100)+'%';$('progress-caption').textContent=done===focusTasks.length?'今天的示例任务都完成了。':'一步一步，就很好。';$('deadlines').innerHTML=tasks.filter(t=>!t.done).sort((a,b)=>a.day-b.day).slice(0,3).map(t=>`<div class="deadline"><span class="timeline-dot"></span><div><strong>${esc(dayText(t.day))} · ${esc(t.time)}</strong><p><button data-detail="${t.id}" style="padding:0;text-align:left">${esc(t.title)}</button></p><small>${esc(t.group)}</small></div></div>`).join('')||'<p class="empty">暂无待办示例</p>';}
function showDialog(content){$('dialog-content').innerHTML=content;paintIcons($('dialog-content'));$('detail-dialog').showModal();}
function showTask(id){const t=tasks.find(x=>x.id===id);if(!t)return;showDialog(`<div class="detail-tags"><span>${esc(t.group)}</span><span>${esc(t.type)}</span><span>示例任务</span></div><h2 id="detail-title">${esc(t.title)}</h2><p>${esc(t.description)}</p><div class="detail-tags"><span>${esc(dayText(t.day))} · ${esc(t.time)}</span><span>${esc(t.duration)}</span></div><h3>下一步怎么做</h3><ol>${t.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><h3>关联资料</h3>${t.material.length?t.material.map(id=>{const m=original.materials.find(x=>x.id===id);return `<a class="detail-material" href="${materialUrl(m.id)}" target="_blank" rel="noopener">${icon('file')}<span>${esc(m.title)}<small> · ${esc(m.format)}</small></span>${icon('arrowUpRight')}</a>`;}).join(''):'<p>这个任务暂时不需要附件。</p>'}<div class="dialog-actions"><button class="primary-button" data-dialog-toggle="${t.id}">${t.done?'恢复到待办':'标记为完成'}</button>${t.sourceUrl?`<a class="secondary-button" href="${esc(t.sourceUrl)}" target="_blank" rel="noopener">${esc(t.source)} ↗</a>`:''}</div><p class="detail-note">当前仅演示布局和交互。日期、任务与资料均为示例；勾选不会提交作业，也不会写入真实任务。</p>`);}
function showAbout(){showDialog('<h2 id="detail-title">先把工作台，布置成你喜欢的样子。</h2><p>这一版只用于讨论布局、栏目和资料入口。没有上传真实任务、课程材料或个人进度。</p><h3>现在可以体验</h3><ol><li>切换今天、全部任务、资料库和已完成</li><li>按类别筛选，或搜索任务和材料</li><li>打开任务详情，查看步骤和关联材料</li><li>勾选演示任务，预览完成归档</li></ol><p class="detail-note">演示勾选只在当前页面生效；刷新或点击“重置演示”会恢复初始内容。公开展示的只有这份样稿。</p>');}
function showLayout(){showDialog('<h2 id="detail-title">每个入口，都有一个清楚的去处。</h2><h3>左侧：找到要看的内容</h3><p>今天看优先事项；全部任务看完整清单；资料库找文章和笔记；已完成保留历史。</p><h3>中间：从任务到行动</h3><p>每个任务包含类别、下一步、截止要求和资料入口。点任务打开详情，点资料进入对应阅读文件。</p><h3>右侧：掌握节奏</h3><p>当天进度、近期截止日期、Canvas / Gradescope / Office Hours，放在随手可见的位置。</p><h3>下一轮可以调整</h3><p>颜色、字体、密度、栏目顺序、任务卡片内容，以及是否需要周视图。布局确认后再接入真实数据。</p>');}
paintIcons();$('month-label').textContent=String(today.getUTCMonth()+1).padStart(2,'0')+' / '+today.getUTCFullYear();$('day-label').textContent=today.getUTCDate();$('weekday-label').textContent=new Intl.DateTimeFormat('zh-CN',{weekday:'long',timeZone:'UTC'}).format(today);$('reading-cards').innerHTML=original.materials.slice(0,2).map(miniMaterial).join('');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){setView(b.dataset.view);return;}if(b.dataset.filter){filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});render();return;}if(b.dataset.detail){showTask(b.dataset.detail);return;}if(b.dataset.toggle){toggle(b.dataset.toggle);return;}if(b.dataset.dialogToggle){$('detail-dialog').close();toggle(b.dataset.dialogToggle);}});
$('search').addEventListener('input',render);$('focus-open').addEventListener('click',()=>showTask('reading'));$('close-dialog').addEventListener('click',()=>$('detail-dialog').close());$('detail-dialog').addEventListener('click',e=>{if(e.target===$('detail-dialog')){const r=$('detail-dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('detail-dialog').close();}});$('reset-demo').addEventListener('click',()=>{tasks=original.tasks.map(t=>({...t}));setView('today');notify('已重置演示内容');});$('about-demo').addEventListener('click',showAbout);$('layout-info').addEventListener('click',showLayout);$('show-hours').addEventListener('click',()=>showDialog('<h2 id="detail-title">Office Hours</h2><p>这里预留教师与助教咨询时间入口。</p><h3>示例排版</h3><div class="detail-material"><span>示例教师<small> · 课程 A</small></span><span>周三 14:00–16:00<br><small>地点待接入</small></span></div><p class="detail-note">以上仅为虚构示例。正式接入后显示课程、人员、时间、地点和预约链接。</p>'));document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)&&!$('detail-dialog').open){e.preventDefault();$('search').focus();}});render();
