'use strict';
// Dates are fixed course dates in America/Chicago. Sources checked on 2026-09-30.
window.WORKLIST = {
  updatedAt: '2026-09-30T16:51:00-05:00',
  scope: '截至 10/14 的课程安排，以及此前未完成事项',
  tasks: [
    {id:'sosc-freedman',course:'SOSC',shortName:'读 Freedman · Statistical Models and Shoe Leather',dueDate:'2026-10-01',deadlineKind:'before-class',done:false,statusVersion:1,note:'1991 正式版，pp. 291–313；课前阅读并带打印材料。',materials:['freedman','sosc-syllabus']},
    {id:'sosc-implication',course:'SOSC',shortName:'读 Implication Analysis',dueDate:'2026-10-01',deadlineKind:'before-class',done:false,statusVersion:1,note:'列于 10/1 日程；大纲排版未清晰区分必读／推荐，归属待确认。',materials:['reserves','sosc-syllabus']},
    {id:'phys-hw1',course:'PHYS',shortName:'HW1',dueDate:'2026-10-05',time:'23:59',done:false,statusVersion:1,note:'8 题，合并成单个 PDF 提交；9/30 核查时尚未提交。',materials:['phys-hw1-pdf','phys-hw1-submit']},
    {id:'sosc-shively',course:'SOSC',shortName:'读 Shively · The Craft of Political Research Ch. 4',dueDate:'2026-10-06',deadlineKind:'before-class',done:false,statusVersion:1,materials:['reserves','sosc-syllabus']},
    {id:'sosc-populism',course:'SOSC',shortName:'读 Meijers & Zaslove · Measuring Populism',dueDate:'2026-10-06',deadlineKind:'before-class',done:false,statusVersion:1,note:'正文 PDF 尚未取得；先保留课程阅读库入口。',materials:['reserves','sosc-syllabus']},
    {id:'math-ps1',course:'MATH',shortName:'PS1',dueDate:'2026-10-07',deadlineKind:'suggested',done:false,statusVersion:1,note:'建议完成日，非硬性 DDL。9 个编号项目；不计分，每周最多交 2 题获取反馈。',materials:['math-ps1','math-policy']},
    {id:'sosc-data',course:'SOSC',shortName:'读 Thinking Clearly about Data Ch. 2 & 4',dueDate:'2026-10-08',deadlineKind:'before-class',done:false,statusVersion:1,note:'Correlation；Correlation Requires Variation。',materials:['reserves','sosc-syllabus']},
    {id:'sosc-quiz',course:'SOSC',shortName:'Quiz 1',dueDate:'2026-10-08',deadlineKind:'in-class',done:false,statusVersion:1,note:'课内 30 分钟，open-note；个人班次待确认。',materials:['sosc-syllabus']},
    {id:'phys-lab',course:'PHYS',shortName:'Intro lab 与实验笔记',dueDate:'2026-10-09',time:'17:30',done:false,statusVersion:1,note:'在家完成测量与分析，只交实验笔记 PDF；9/30 核查时尚未提交。',materials:['lab-template','lab-guide','phys-lab-submit']},
    {id:'phys-hw2',course:'PHYS',shortName:'HW2',dueDate:'2026-10-12',time:'23:59',state:'waiting',done:false,statusVersion:1,note:'10/6 00:00 开放，题目尚不可获取。',materials:['phys-hw2']},
    {id:'sosc-rohrer',course:'SOSC',shortName:'读 Rohrer · Correlations and Causation',dueDate:'2026-10-13',deadlineKind:'before-class',done:false,statusVersion:1,note:'Thinking clearly about correlations and causation: Graphical causal models for observational data（2018）。',materials:['reserves','sosc-syllabus']},
    {id:'sosc-imbens',course:'SOSC',shortName:'读 Imbens & Rubin · Causal Inference Ch. 1',dueDate:'2026-10-13',deadlineKind:'before-class',done:false,statusVersion:1,materials:['reserves','sosc-syllabus']},
    {id:'cmsc-hw1',course:'CMSC',shortName:'HW1',dueDate:'2026-10-14',state:'waiting',done:false,statusVersion:1,note:'Gradescope 尚未发布作业；官网计划 10/5 或 10/6 发布，10/14 截止，具体时刻待公布。',materials:['cmsc-gradescope','cmsc-syllabus']},
    {id:'phys-reading',course:'PHYS',shortName:'读教材 Ch. 1–3',dueDate:null,done:false,statusVersion:1,note:'第 1 周阅读要求；未列单独截止时刻，教材全文尚未获取。',materials:['phys-week1']},
    {id:'phys-reading2',course:'PHYS',shortName:'读教材 Ch. 3–4',dueDate:null,done:false,statusVersion:1,note:'第 2 周阅读要求；未列单独截止时刻。',materials:['phys-week2']},
    {id:'phys-reading3',course:'PHYS',shortName:'读教材 Ch. 5',dueDate:null,done:false,statusVersion:1,note:'第 3 周阅读要求；未列单独截止时刻。',materials:['phys-week3']},
    {id:'new-notes',course:'课程',shortName:'整理 9/30 新课笔记',dueDate:null,state:'suggestion',done:false,statusVersion:1,note:'建议事项：整理后续课次笔记；第一节课笔记已完成。',materials:['math-course','cmsc-syllabus']},
    {id:'syllabus',course:'课程',shortName:'阅读四门 Syllabus',dueDate:null,done:false,statusVersion:1,materials:['math-syllabus','cmsc-syllabus','phys-syllabus','sosc-syllabus']},
    {id:'email-oh',course:'CMSC',shortName:'给教授发邮件询问 Office Hour',dueDate:null,done:false,statusVersion:1,note:'此前待办，邮件尚未发送。常规 Office Hours 已查到，见右侧入口；是否还需发信待确认。',materials:['cmsc-syllabus']},
    {id:'ra',course:'RA',shortName:'任务待补充',dueDate:null,state:'waiting',done:false,statusVersion:1,note:'保留为近期事项；具体工作、进度及资料尚待补充。',materials:[]},
    {id:'julia',course:'课外',shortName:'寻找 Exile: According to Julia 英译 PDF',dueDate:null,state:'waiting',done:false,statusVersion:1,note:'Betty Wilson 英译本；尚未找到可核实的全文 PDF，馆藏入口为纸质书。',materials:['julia-catalog']},
    {id:'sosc-first',course:'SOSC',shortName:'听 NPR ＋ 读 Mostly Harmless Econometrics Ch. 1',dueDate:'2026-09-29',deadlineKind:'before-class',done:true,statusVersion:1,note:'9/30 已确认听读完成。',materials:['npr','reserves']},
    {id:'cmsc-notes1',course:'CMSC',shortName:'整理第一节课笔记',dueDate:null,done:true,statusVersion:1,note:'9/30 已确认完成。',materials:['cmsc-old-notes']},
    {id:'math-notes1',course:'MATH',shortName:'整理第一节课笔记',dueDate:null,done:true,statusVersion:1,note:'9/30 已确认完成。',materials:['math-lecture1']}
  ],
  materials: {
    'freedman':{title:'Freedman 1991 · PDF',url:'https://www.sas.rochester.edu/psc/clarke/214/Freedman91.pdf'},
    'sosc-syllabus':{title:'SOSC Syllabus',url:'https://canvas.uchicago.edu/courses/74986'},
    'reserves':{title:'Library Reserves · 阅读库（登录）',url:'https://canvas.uchicago.edu/courses/74986/external_tools/50'},
    'phys-hw1-pdf':{title:'HW1 题目 PDF（登录）',url:'https://canvas.uchicago.edu/courses/74238/files/15813492?wrap=1'},
    'phys-hw1-submit':{title:'HW1 要求与提交',url:'https://canvas.uchicago.edu/courses/74238/assignments/908615'},
    'math-ps1':{title:'PS1 题目 PDF',url:'https://www.dropbox.com/scl/fi/82yu69o21lypbiso29lik/pset1.pdf?rlkey=0p4ya6sfuf3klpht51tm4rk30&dl=0'},
    'math-policy':{title:'作业反馈规则',url:'https://canvas.uchicago.edu/courses/75102/discussion_topics/1016628'},
    'math-syllabus':{title:'MATH Syllabus PDF',url:'https://www.dropbox.com/scl/fi/bv2xrsrrb2846mvyf040l/syllabus257.pdf?rlkey=9ofjaipzdto8ewl2iavsix6w0&st=c562qyic&dl=0'},
    'math-course':{title:'MATH 课程页',url:'https://canvas.uchicago.edu/courses/75102'},
    'math-lecture1':{title:'Lecture 1 PDF',url:'https://www.dropbox.com/scl/fi/jbp2bjijlihbj90riw99w/Lecture1.pdf?rlkey=42mlm059opau6legp2i8bkeom&st=awih5zlh&dl=0'},
    'lab-template':{title:'实验笔记模板',url:'https://docs.google.com/document/d/18q_HWUvWTKd5L4JRuV-UxjrGdcIarLXUY3CsnUo4-jc/edit'},
    'lab-guide':{title:'PHYS 实验说明入口',url:'https://www.physlab-wiki.com/phylabs/lab_courses/phys-120_130-wiki-home'},
    'phys-lab-submit':{title:'Intro lab 要求与提交',url:'https://canvas.uchicago.edu/courses/74238/assignments/908682'},
    'phys-hw2':{title:'HW2 · 10/6 开放',url:'https://canvas.uchicago.edu/courses/74238/assignments/908619'},
    'phys-syllabus':{title:'PHYS Syllabus',url:'https://canvas.uchicago.edu/courses/74238'},
    'phys-week1':{title:'第 1 周阅读要求',url:'https://canvas.uchicago.edu/courses/74238/modules/items/3209056'},
    'phys-week2':{title:'第 2 周阅读要求',url:'https://canvas.uchicago.edu/courses/74238/modules/items/3209776'},
    'phys-week3':{title:'第 3 周阅读要求',url:'https://canvas.uchicago.edu/courses/74238/modules/items/3209777'},
    'cmsc-gradescope':{title:'CMSC Gradescope',url:'https://www.gradescope.com/courses/1417716'},
    'cmsc-syllabus':{title:'CMSC 官网与 Syllabus',url:'https://people.cs.uchicago.edu/~razborov/teaching/autumn26.html'},
    'cmsc-old-notes':{title:'2018 讲义 PDF · 仅作参考',url:'https://people.cs.uchicago.edu/~razborov/teaching/HonorsDiscreteMath/notes18.pdf'},
    'julia-catalog':{title:'芝大纸质书馆藏',url:'https://catalog.lib.uchicago.edu/vufind/Record/5056629'},
    'npr':{title:'NPR 播客与文字',url:'https://www.npr.org/2021/10/12/1045462268/a-nobel-prize-for-an-economics-revolution'}
  },
  officeHours: [
    {person:'Alexander Razborov · 教授',time:'周一 14:00–16:00',place:'Ryerson 360G'},
    {person:'Nikhil Patel · TA',time:'周二 15:00–17:00',place:'Crerar common space 2C；二楼左转，接近内部大楼梯处'},
    {person:'Seamus Lavine · TA',time:'周五 16:00–18:00',place:'Crerar 207'}
  ]
};
